version: "3.2"
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - USER=$USER
      - ACCESS_TOKEN=$ACCESS_TOKEN
      - ACCESS_TOKEN_SECRET=$ACCESS_TOKEN_SECRET
      - API_KEY=$API_KEY
      - API_KEY_SECRET=$API_KEY_SECRET
    volumes:
      tweets.db:/
