version: "3.2"
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - USER_NAME=$USER_NAME
      - ACCESS_TOKEN=$ACCESS_TOKEN
      - ACCESS_TOKEN_SECRET=$ACCESS_TOKEN_SECRET
      - API_KEY=$API_KEY
      - API_KEY_SECRET=$API_KEY_SECRET
      - AI=$AI
    volumes:
      - ./tweets.db:/tweets.db
